name: mylib
description: "A Flutter Rust Package"
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  rust_lib_mylib:
    path: rust_builder
  flutter_rust_bridge: 2.10.0

